djangoAplication/baza/baza/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from adminBaza import views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url("^$", views.indexView, name='index'),
    url(r"^login/$", views.loginView, name='login'),
    url(r"^register/$", views.registerView, name='register'),
    url(r"^index/$", views.indexView, name='index'),
    url(r"^logout/$", views.logoutView, name='logout'),

    url(r"^person/add/$", views.personAddView, name='personAdd'),
    url(r"^person/add/ok/$", views.personAddOKView, name='personAddOK'),
    url(r"^person/preview/$", views.personPreviewView, name='personPreview'),
    url(r"^person/edit/(?P<personId>\d+)$", views.personEditView, name='personEdit'),
    url(r"^person/edit/ok$", views.personEditOKView, name='personEditOK'),
    url(r"^person/detail/(?P<personId>\d+)$", views.personDetailView, name='personDetail'),

    url(r"^pilgrimage/add/$", views.pilgrimageAddView, name='pilgrimageAdd'),
    url(r"^pilgrimage/add/ok/$", views.pilgrimageAddOKView, name='pilgrimageAddOK'),
    url(r"^pilgrimage/preview/", views.pilgrimagePreviewView, name='pilgrimagePreview'),
    url(r"^pilgrimage/edit/(?P<pilgrimageId>\d+)$", views.pilgrimageEditView, name='pilgrimageEdit'),
    url(r"^pilgrimage/edit/ok$", views.pilgrimageEditOKView, name='pilgrimageEditOK'),
    url(r"^pilgrimage/detail/(?P<pilgrimageId>\d+)$", views.pilgrimageDetailView, name='pilgrimageDetail'),

    url(r"^pilgrim/add/$", views.pilgrimAddView, name='pilgrimAdd'),
    url(r"^pilgrim/add/ok/$", views.pilgrimAddOKView, name='pilgrimAddOK'),
    url(r"^pilgrim/preview/", views.pilgrimPreviewView, name='pilgrimPreview'),
    url(r"^pilgrim/edit/(?P<pilgrimId>\d+)$", views.pilgrimEditView, name='pilgrimEdit'),
    url(r"^pilgrim/edit/ok$", views.pilgrimEditOKView, name='pilgrimEditOK'),
    url(r"^pilgrim/detail/(?P<pilgrimId>\d+)$", views.pilgrimDetailView, name='pilgrimDetail'),

    url(r"^pilgrim/generateId/(?P<pilgrimId>\d+)$", views.generatePilgrimIdView, name='generatePilgrimId'),

    url(r"^organiser/add/$", views.organiserAddView, name='organiserAdd'),
    url(r"^organiser/add/ok/$", views.organiserAddOKView, name='organiserAddOK'),
    url(r"^organiser/preview/", views.organiserPreviewView, name='organiserPreview'),
    url(r"^organiser/edit/(?P<organiserId>\d+)$", views.organiserEditView, name='organiserEdit'),
    url(r"^organiser/edit/ok$", views.organiserEditOKView, name='organiserEditOK'),
    url(r"^organiser/detail/(?P<organiserId>\d+)$", views.organiserDetailView, name='organiserDetail'),

    url(r"^organiser/generateId/(?P<organiserId>\d+)$", views.generateOrganiserIdView, name='generateOrganiserId'),

    url(r"^organiser/extraId$", views.generateExtraOrganiserIdView, name='extraOrganiserId'),
    url(r"^pilgrim/extraId$", views.generateExtraPilgrimIdView, name='extraPilgrimId'),

    url(r"^help/$", views.helpView, name='help'),


    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djangoAplication/baza/adminBaza/models.py
# -*- coding: utf-8
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.

class Person(models.Model):
    """
    This class provides model for every person which can occur in database. It's needed to enter person object before ie. registering person to pilgrimage as pilgrim or organiser.
    """
    SEX_CHOICES = (('M', 'Man'), ('W', 'Woman'))

    name = models.CharField(max_length=20, help_text="First name of the person.")
    surname = models.CharField(max_length=50, help_text="Family name of the person.")
    pesel = models.DecimalField(max_digits=11, decimal_places=0, unique=True, help_text="PESEL of the person.")
    birth = models.DateField(help_text="Date of birth of person.")
    sex = models.CharField(max_length=1, choices=SEX_CHOICES, help_text="Gender of the person")
    address = models.CharField(max_length=200, help_text="Address of residence oi the person.")
    email = models.EmailField(blank=True, help_text="E-mail address of the person.")
    phone = models.IntegerField(null=True, help_text="Phone number of the person.")
    comments = models.CharField(max_length=400, blank=True, help_text="Any comment relative to the person.")

    def clean_fields(self, exclude=None):
        """
        This method provides extra check for constraints for the Person model. Merged with field property checks if PESEL value has exactly 11 digits.
        :param exclude: None - No fields are excluded.
        :raises Raises ValidationError if validating of PESEL value fails.
        """
        if self.pesel<=(10**10):
            raise ValidationError('Insert proper PESEL value.')

    def __unicode__(self):
        """
        Returns unicode object for model returning catenation of name, durname and PESEL value.
        :return: unicode objcet for model.
        """
        return self.name + " " + self.surname + " " + unicode(self.pesel);


class Pilgrimage(models.Model):
    """
    This class represents model for the pilgrimage.
    """
    name = models.CharField(max_length=200, help_text="Title or name of the pilgrimage")
    dateFrom = models.DateField(help_text="Start date.")
    dateTo = models.DateField(help_text="End date.")

    def clean(self):
        """
        Check the constraints for objects. Checks if begin date is before end date
        :raises Raises ValidationError if dates are not correct.
        """
        if self.dateFrom >= self.dateTo:
            raise ValidationError('Start date is after end date')

    def __unicode__(self):
        """
        Return unicode object for model returning name and year of begin date of pilgrimage.
        :return: unicode objcet for model.
        """
        return self.name + " " + unicode(self.dateFrom.year)


class Group(models.Model):
    """
    This class represents model for the group in the pilgrimages, smaller subgroup of all the people linked with exact parish.
    """
    nr = models.IntegerField(help_text="Number of the group.");
    name = models.CharField(max_length=50, help_text="Name of the group.")
    parish = models.CharField(max_length=200, help_text="Parish description linked with the group.")
    comments = models.CharField(max_length=400, blank=True, help_text="Any comment associated with the group.")

    def __unicode__(self):
        """
        Returns unicode object for model returning catenation of number of group and name.
        :return: unicode object for model.
        """
        return unicode(self.nr) + " - " + unicode(self.name)


class FunctionInGroup(models.Model):
    """
    This class represents model for the organising functions performed in the proper groups.
    """
    name = models.CharField(max_length=50, help_text="Name of the function - short description.")
    comments = models.CharField(max_length=200, blank=True, help_text="Any comment associated with the function.")

    def __unicode__(self):
        """
        Returns unicode object for model returning its name.
        :return: unicode object for model.
        """
        return self.name


class Pilgrim(models.Model):
    """
    This class represents model for pilgrim participating in specific pilgrimage in specific group and properties. This class can be treated as model for signing up action to concrete pilgrimage by person defined in :model:`adminBaza.Person` model.
    """
    id_person = models.ForeignKey(Person, help_text="Foreign key to person object signing up to pilgrimage.")
    id_pilgrimage = models.ForeignKey(Pilgrimage, help_text="Foreign key to pilgrimage to which person is signing up.")
    id_group = models.ForeignKey(Group, help_text="Foreign key to group object.")
    tent = models.BooleanField(help_text="Does pilgrim has own tent?")
    functions = models.ManyToManyField(FunctionInGroup, null=True, blank=True, help_text="Many-to-many foreign key if pilgrim has special organising functions in group.")
    comments = models.CharField(max_length=400, blank=True, help_text="Any comment.")


class FunctionOrganiser(models.Model):
    """
    This class represents model for this organising function performed by main organisers - the base."
    """
    name = models.CharField(max_length=50, help_text="Name of the function - short description.")
    comments = models.CharField(max_length=200, blank=True, help_text="Any comment.")

    def __unicode__(self):
        """
        Returns unicode object for model returning its name.
        :return: unicode object for model.
        """
        return self.name


class Organiser(models.Model):
    """
    This class represents model for organiser participating in specific pilgrimage. This class can be treated as model for signing up action to concrete pilgrimage by person defined in :model:`adminBaza.Person` model.
    """
    id_person = models.ForeignKey(Person, help_text="Foreign key to person which is organiser in this pilgrimage.")
    id_pilgrimage = models.ForeignKey(Pilgrimage, help_text="Foreign key to pilgrimage in which person is organiser.")
    id_function = models.ForeignKey(FunctionOrganiser, help_text="Foreign key to function which person undertakes.")

djangoAplication/baza/baza/templates/person/person_add.html
{% extends "main.html" %}
{% block content %}
	Insert personal data of new person:
	<form action="" method="post">
        <table>
			{{ form.as_table }}
        <tr><td></td><td><input type="submit" value="Submit"></td></tr>
        </table>
        {% csrf_token %}
	</form>
{% endblock %}

djangoAplication/baza/baza/templates/person/person_add_ok.html
{% extends "main.html" %}
{% block content %}
	<p><b>Thank You. Person was successfully added to database.</b></p>
	<p>For adding another one, go to section <a href="{% url 'personAdd' %}">add.</a><br/>
	For seeing complete list of all people, go to section <a href="{% url "personPreview" %}">preview.</a>
	</p>
{% endblock %}

djangoAplication/baza/baza/templates/person/person_detail.html
{% extends "main.html" %}
{% block content %}


	<table>
	<tr><td>Id</td><td id="value_id">{{ person.id }}</td></tr>
    <tr><td>First Name</td><td id="value_id">{{ person.firstName }}</td></tr>
    <tr><td>Surname</td><td id="value_id">{{ person.surname }}</td></tr>
    <tr><td>PESEL</td><td id="value_id">{{ person.pesel }}</td></tr>
    <tr><td>Birth</td><td id="value_id">{{ person.birth }}</td></tr>
    <tr><td>Sex</td><td id="value_id">{{ person.get_sex_display }}</td></tr>
    <tr><td>Address</td><td id="value_id">{{ person.address }}</td></tr>
    <tr><td>e-mail</td><td id="value_id">{{ person.email }}</td></tr>
    <tr><td>Phone</td><td id="value_id">{{ person.phone }}</td></tr>
    <tr><td>Comments</td><td id="value_id">{{ person.comments }}</td></tr>
    <tr><td><a href="{% url 'personEdit' person.id %}" id="edit_id">Edit</a></td></tr>
	</table>

{% endblock %}

djangoAplication/baza/baza/templates/person/person_edit.html
{% extends "main.html" %}
{% block content %}
	Here You can edit data of given person:
	<form action="" method="post">
        <table>
			{{ form.as_table }}
        <tr><td></td><td><button type="submit" name="edit" value="True">Edit</button></td></tr>
        </table>
        <input type="hidden" name="personId" value="{{ personId }}" />
        {% csrf_token %}
	</form>
{% endblock %}

djangoAplication/baza/baza/templates/person/person_edit_ok.html
{% extends "main.html" %}
{% block content %}
	<p><b>Thank You. Person personal data was successfully changed in database.</b></p>
	<p>For adding another one, go to section <a href="{% url 'personAdd' %}">add.</a><br/>
	For seeing complete list of all pilgrimages, go to section <a href="{% url "personPreview" %}">preview.</a>
	</p>
{% endblock %}

djangoAplication/baza/baza/templates/person/person_preview.html
{% extends "main.html" %}
{% load staticfiles %}
{% block extracss %}
    <link rel="Stylesheet" type="text/css" href="{% static "styleFilter.css" %}">
{% endblock %}
{% block content %}

    <div class="toggle filter_area">
    <a href="#" class="click-area description">CLICK FOR FILTER</a>
    <div class="toggle-area">
	    {{ filterForm.non_field_errors }}
        <form action="" method="POST" id="filter_form">
        {% csrf_token %}
        <table>
            <tr><td>{{ filterForm.name.label_tag }}</td><td>{{ filterForm.name }}</td><td>{{ filterForm.name.errors }}</td></tr>
            <tr><td>{{ filterForm.surname.label_tag }}</td><td>{{ filterForm.surname }}</td><td>{{ filterForm.surname.errors }}</td></tr>
            <tr><td>{{ filterForm.pesel.label_tag }}</td><td>{{ filterForm.pesel }}</td><td>{{ filterForm.pesel.errors }}</td></tr>
        </table>
        <ul class="help_text">
            <li>{{ filterForm.name.help_text }}</li>

            {% if filterForm.name.help_text != filterForm.surname.help_text %}
            <li>{{ filterForm.surname.help_text }}</li>
            {% endif %}
            {% if filterForm.pesel.help_text != filterForm.name.help_text and filterForm.pesel.help_text != filterForm.surname.help_text %}
            <li>{{ filterForm.pesel.help_text }}</li>
            {% endif %}

        </ul>
        <button type="submit" name="filter" value="True">Filter</button>
        </form>
    </div>
    </div>


	<table border="black">
	<tr><td>id</td><td>Name</td><td>Surname</td><td>Date of birth</td><td>PESEL</td></tr>

    {{ values.as_table }}
    {% for row in values %}
        <tr><td>{{ row.id }}</td><td>{{ row.name }}</td><td><a href="{%  url 'personDetail' row.id %}">{{ row.surname }}</a></td><td>{{ row.birth }}</td><td>{{ row.pesel }}</td></tr>
	{% endfor %}
	</table>
{% endblock %}